name: Holocron Deploy
on:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read
  deployments: write
  statuses: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Holocron
      url: ${{ steps.deploy.outputs.holocron_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Deploy
        id: deploy
        run: bunx holocron deploy
        env:
          HOLOCRON_KEY: ${{ secrets.HOLOCRON_KEY }}
      - name: Set commit status
        if: steps.deploy.outputs.holocron_url
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state=success \
            -f target_url="${{ steps.deploy.outputs.holocron_url }}" \
            -f description="Docs website deployment" \
            -f context=Holocron
